on:
    push:
        paths:
        - 'Basic Crud/olt/crud/**' 
name: 🚀 Deploy website on push
  
jobs:
    web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
  
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_36739437
          password: ${{ secrets.password }}
          protocol: ftps
          port: 21
          local-dir: Basic Crud/olt/crud/  
          server-dir: htdocs/
